version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: affiliate_leads
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: affiliate-api
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=affiliate_leads
      - DB_PORT=5432
      - DB_SSLMODE=disable
      - JWT_SECRET=Wa8wDrAuSHy31FvN7MgZQUUe8tTt5yqmsUraBa7E0XA=
    ports:
      - "8080:8080"
    networks:
      - default

volumes:
  db_data:
